CXX = clang++

demo0: 
	$(CXX) mains_to_test/imp_main_0.cpp -o run0 && \
	$(CXX) reference_mains/ref_main_0.cpp -o ref0

demo1: 
	$(CXX) mains_to_test/imp_main_1.cpp -o run1 && \
	$(CXX) reference_mains/ref_main_1.cpp -o ref1

demo2: 
	$(CXX) mains_to_test/imp_main_2.cpp -o run2 && \
	$(CXX) reference_mains/ref_main_2.cpp -o ref2

demo3: 
	$(CXX) mains_to_test/imp_main_3.cpp -o run3 && \
	$(CXX) reference_mains/ref_main_3.cpp -0 ref3