# example diff test config file
# matt russell

[config]
exec           = "run"             # executable file name
ref_exec       = "reference"       # reference executable file name
build_target   = "build"           # command to run make with: i.e. 'make build'
stdin_dir      = "testfiles/stdin" # directory for stdin files 

[tests.test1]
input_args   = ["infiles/file1", "somearg"] # ./MetroSim infiles/file1 somearg     (default=[])
stdin_file   = "test1"              # MetroSim ... < test1        (default=None)
output_files = ["somearg"]          # 'somearg' is written to by the program.
run_valgrind = "True"               # [optional] run valgrind?    (default=True)
diff_stderr  = "False"              # [optional] diff stderr with the reference?

[tests.test2]